authors:
  vanderoost:
    name: Richard van der Oost
    description: I automate business operations with software and LLMs
    avatar: https://avatars.githubusercontent.com/u/11665420?v=4
    url: https://www.linkedin.com/in/richardvdoost/
